version: '3.9'

services:
  db:
    image: postgres:13  # You can use any version of PostgreSQL
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foxy_walk
      POSTGRES_DB: ode_to_a_mixtape_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
